// DO NOT EDIT! This file is auto-generated by build.rs.
// Instead, update ebml.xml and ebml_matroska.xml
use crate::ebml::ebml_elements;
ebml_elements! {
    /// Set the EBML characteristics of the data to follow. Each EBML document has to start with this.
    name = Ebml, original_name = "EBML", id = 0x1A45DFA3, variant = Master;
    /// The version of EBML parser used to create the file.
    name = EbmlVersion, original_name = "EBMLVersion", id = 0x4286, variant = Unsigned;
    /// The minimum EBML version a parser has to support to read this file.
    name = EbmlReadVersion, original_name = "EBMLReadVersion", id = 0x42F7, variant = Unsigned;
    /// The maximum length of the IDs you'll find in this file (4 or less in Matroska).
    name = EbmlMaxIdLength, original_name = "EBMLMaxIDLength", id = 0x42F2, variant = Unsigned;
    /// The maximum length of the sizes you'll find in this file (8 or less in Matroska). This does not override the element size indicated at the beginning of an element. Elements that have an indicated size which is larger than what is allowed by EBMLMaxSizeLength shall be considered invalid.
    name = EbmlMaxSizeLength, original_name = "EBMLMaxSizeLength", id = 0x42F3, variant = Unsigned;
    /// A string that describes the type of document that follows this EBML header. 'matroska' in our case or 'webm' for webm files.
    name = DocType, original_name = "DocType", id = 0x4282, variant = String;
    /// The version of DocType interpreter used to create the file.
    name = DocTypeVersion, original_name = "DocTypeVersion", id = 0x4287, variant = Unsigned;
    /// The minimum DocType version an interpreter has to support to read this file.
    name = DocTypeReadVersion, original_name = "DocTypeReadVersion", id = 0x4285, variant = Unsigned;
    /// A DocTypeExtension adds extra Elements to the main DocType+DocTypeVersion	tuple it's attached to. An EBML Reader **MAY** know these extra Elements and how to use them. A DocTypeExtension **MAY** be used to iterate between	experimental Elements before they are integrated into a regular	DocTypeVersion. Reading one DocTypeExtension version of a DocType+DocTypeVersion tuple doesn't imply one should be able to read upper versions of this DocTypeExtension.
    name = DocTypeExtension, original_name = "DocTypeExtension", id = 0x4281, variant = Master;
    /// The name of the DocTypeExtension to differentiate it from other DocTypeExtensions of the same DocType+DocTypeVersion tuple. A DocTypeExtensionName value **MUST** be unique within the EBML Header.
    name = DocTypeExtensionName, original_name = "DocTypeExtensionName", id = 0x4283, variant = String;
    /// The version of the DocTypeExtension. Different DocTypeExtensionVersion values of the same DocType + DocTypeVersion + DocTypeExtensionName tuple **MAY** contain completely different sets of extra Elements. An EBML Reader **MAY** support multiple versions	of the same tuple, only one version of the tuple, or not support the tuple at all.
    name = DocTypeExtensionVersion, original_name = "DocTypeExtensionVersion", id = 0x4284, variant = Unsigned;
    /// Used to void damaged data, to avoid unexpected behaviors when using damaged data. The content is discarded. Also used to reserve space in a sub-element for later use.
    name = Void, original_name = "Void", id = 0xEC, variant = Binary;
    /// The CRC is computed on all the data of the Master element it's in. The CRC element should be the first in it's parent master for easier reading. All level 1 elements should include a CRC-32. The CRC in use is the IEEE CRC32 Little Endian.
    name = Crc32, original_name = "CRC-32", id = 0xBF, variant = Binary;
    /// The Root Element that contains all other Top-Level Elements; see (#data-layout).
    name = Segment, original_name = "Segment", id = 0x18538067, variant = Master;
    /// Contains seeking information of Top-Level Elements; see (#data-layout).
    name = SeekHead, original_name = "SeekHead", id = 0x114D9B74, variant = Master;
    /// Contains a single seek entry to an EBML Element.
    name = Seek, original_name = "Seek", id = 0x4DBB, variant = Master;
    /// The binary EBML ID of a Top-Level Element.
    name = SeekId, original_name = "SeekID", id = 0x53AB, variant = Binary;
    /// The Segment Position ((#segment-position)) of a Top-Level Element.
    name = SeekPosition, original_name = "SeekPosition", id = 0x53AC, variant = Unsigned;
    /// Contains general information about the Segment.
    name = Info, original_name = "Info", id = 0x1549A966, variant = Master;
    /// A randomly generated unique ID to identify the Segment amongst many others (128 bits).
    /// It is effectively a Universally Unique IDentifier stored in binary form [@!RFC4122].
    /// If the Segment is a part of a Linked Segment, then this Element is **REQUIRED**.
    name = SegmentUuid, original_name = "SegmentUUID", id = 0x73A4, variant = Binary;
    /// A filename corresponding to this Segment.
    name = SegmentFilename, original_name = "SegmentFilename", id = 0x7384, variant = Utf8;
    /// A unique ID to identify the previous Segment of a Linked Segment (128 bits).
    /// Like the SegmentUUID, it is a Universally Unique IDentifier stored in binary form [@!RFC4122].
    /// If the Segment is a part of a Linked Segment that uses Hard Linking ((#hard-linking)),
    /// then either the PrevUUID or the NextUUID Element is **REQUIRED**. If a Segment contains a PrevUUID but not a NextUUID,
    /// then it **MAY** be considered as the last Segment of the Linked Segment. The PrevUUID **MUST NOT** be equal to the SegmentUUID.
    name = PrevUuid, original_name = "PrevUUID", id = 0x3CB923, variant = Binary;
    /// A filename corresponding to the file of the previous Linked Segment.
    /// Provision of the previous filename is for display convenience,
    /// but PrevUUID **SHOULD** be considered authoritative for identifying the previous Segment in a Linked Segment.
    name = PrevFilename, original_name = "PrevFilename", id = 0x3C83AB, variant = Utf8;
    /// A unique ID to identify the next Segment of a Linked Segment (128 bits).
    /// Like the SegmentUUID, it is a Universally Unique IDentifier stored in binary form [@!RFC4122].
    /// If the Segment is a part of a Linked Segment that uses Hard Linking ((#hard-linking)),
    /// then either the PrevUUID or the NextUUID Element is **REQUIRED**. If a Segment contains a NextUUID but not a PrevUUID,
    /// then it **MAY** be considered as the first Segment of the Linked Segment. The NextUUID **MUST NOT** be equal to the SegmentUUID.
    name = NextUuid, original_name = "NextUUID", id = 0x3EB923, variant = Binary;
    /// A filename corresponding to the file of the next Linked Segment.
    /// Provision of the next filename is for display convenience,
    /// but NextUUID **SHOULD** be considered authoritative for identifying the Next Segment.
    name = NextFilename, original_name = "NextFilename", id = 0x3E83BB, variant = Utf8;
    /// A randomly generated unique ID that all Segments of a Linked Segment **MUST** share (128 bits).
    /// It is effectively a Universally Unique IDentifier stored in binary form [@!RFC4122].
    /// If the Segment Info contains a `ChapterTranslate` element, this Element is **REQUIRED**.
    name = SegmentFamily, original_name = "SegmentFamily", id = 0x4444, variant = Binary;
    /// The mapping between this `Segment` and a segment value in the given Chapter Codec.
    /// Chapter Codec may need to address different segments, but they may not know of the way to identify such segment when stored in Matroska.
    /// This element and its child elements add a way to map the internal segments known to the Chapter Codec to the Segment IDs in Matroska.
    /// This allows remuxing a file with Chapter Codec without changing the content of the codec data, just the Segment mapping.
    name = ChapterTranslate, original_name = "ChapterTranslate", id = 0x6924, variant = Master;
    /// The binary value used to represent this Segment in the chapter codec data.
    /// The format depends on the ChapProcessCodecID used; see (#chapprocesscodecid-element).
    name = ChapterTranslateId, original_name = "ChapterTranslateID", id = 0x69A5, variant = Binary;
    /// This `ChapterTranslate` applies to this chapter codec of the given chapter edition(s); see (#chapprocesscodecid-element).
    name = ChapterTranslateCodec, original_name = "ChapterTranslateCodec", id = 0x69BF, variant = Unsigned;
    /// Specify a chapter edition UID on which this `ChapterTranslate` applies.
    /// When no `ChapterTranslateEditionUID` is specified in the `ChapterTranslate`, the `ChapterTranslate` applied to all chapter editions found in the Segment using the given `ChapterTranslateCodec`.
    name = ChapterTranslateEditionUid, original_name = "ChapterTranslateEditionUID", id = 0x69FC, variant = Unsigned;
    /// Base unit for Segment Ticks and Track Ticks, in nanoseconds. A TimestampScale value of 1.000.000 means scaled timestamps in the Segment are expressed in milliseconds; see (#timestamps) on how to interpret timestamps.
    name = TimestampScale, original_name = "TimestampScale", id = 0x2AD7B1, variant = Unsigned;
    /// Duration of the Segment, expressed in Segment Ticks which is based on TimestampScale; see (#timestamp-ticks).
    name = Duration, original_name = "Duration", id = 0x4489, variant = Float;
    /// The date and time that the Segment was created by the muxing application or library.
    name = DateUtc, original_name = "DateUTC", id = 0x4461, variant = Date;
    /// General name of the Segment.
    name = Title, original_name = "Title", id = 0x7BA9, variant = Utf8;
    /// Muxing application or library (example: "libmatroska-0.4.3").
    /// Include the full name of the application or library followed by the version number.
    name = MuxingApp, original_name = "MuxingApp", id = 0x4D80, variant = Utf8;
    /// Writing application (example: "mkvmerge-0.3.3").
    /// Include the full name of the application followed by the version number.
    name = WritingApp, original_name = "WritingApp", id = 0x5741, variant = Utf8;
    /// The Top-Level Element containing the (monolithic) Block structure.
    name = Cluster, original_name = "Cluster", id = 0x1F43B675, variant = Master;
    /// Absolute timestamp of the cluster, expressed in Segment Ticks which is based on TimestampScale; see (#timestamp-ticks).
    /// This element **SHOULD** be the first child element of the Cluster it belongs to,
    /// or the second if that Cluster contains a CRC-32 element ((#crc-32)).
    name = Timestamp, original_name = "Timestamp", id = 0xE7, variant = Unsigned;
    /// The list of tracks that are not used in that part of the stream.
    /// It is useful when using overlay tracks on seeking or to decide what track to use.
    name = SilentTracks, original_name = "SilentTracks", id = 0x5854, variant = Master;
    /// One of the track number that are not used from now on in the stream.
    /// It could change later if not specified as silent in a further Cluster.
    name = SilentTrackNumber, original_name = "SilentTrackNumber", id = 0x58D7, variant = Unsigned;
    /// The Segment Position of the Cluster in the Segment (0 in live streams).
    /// It might help to resynchronise offset on damaged streams.
    name = Position, original_name = "Position", id = 0xA7, variant = Unsigned;
    /// Size of the previous Cluster, in octets. Can be useful for backward playing.
    name = PrevSize, original_name = "PrevSize", id = 0xAB, variant = Unsigned;
    /// Similar to Block, see (#block-structure), but without all the extra information,
    /// mostly used to reduced overhead when no extra feature is needed; see (#simpleblock-structure) on SimpleBlock Structure.
    name = SimpleBlock, original_name = "SimpleBlock", id = 0xA3, variant = Binary;
    /// Basic container of information containing a single Block and information specific to that Block.
    name = BlockGroup, original_name = "BlockGroup", id = 0xA0, variant = Master;
    /// Block containing the actual data to be rendered and a timestamp relative to the Cluster Timestamp;
    /// see (#block-structure) on Block Structure.
    name = Block, original_name = "Block", id = 0xA1, variant = Binary;
    /// A Block with no data. It **MUST** be stored in the stream at the place the real Block would be in display order.
    name = BlockVirtual, original_name = "BlockVirtual", id = 0xA2, variant = Binary;
    /// Contain additional binary data to complete the main one; see Codec BlockAdditions section of [@?MatroskaCodec] for more information.
    /// An EBML parser that has no knowledge of the Block structure could still see and use/skip these data.
    name = BlockAdditions, original_name = "BlockAdditions", id = 0x75A1, variant = Master;
    /// Contain the BlockAdditional and some parameters.
    name = BlockMore, original_name = "BlockMore", id = 0xA6, variant = Master;
    /// Interpreted by the codec as it wishes (using the BlockAddID).
    name = BlockAdditional, original_name = "BlockAdditional", id = 0xA5, variant = Binary;
    /// An ID to identify how to interpret the BlockAdditional data; see Codec BlockAdditions section of [@?MatroskaCodec] for more information.
    /// A value of 1 indicates that the meaning of the BlockAdditional data is defined by the codec.
    /// Any other value indicates the meaning of the BlockAdditional data is found in the BlockAddIDType found in the TrackEntry.
    /// Each BlockAddID value **MUST** be unique between all BlockMore elements found in a BlockAdditions.
    /// To keep MaxBlockAdditionID as low as possible, small values **SHOULD** be used.
    name = BlockAddId, original_name = "BlockAddID", id = 0xEE, variant = Unsigned;
    /// The duration of the Block, expressed in Track Ticks; see (#timestamp-ticks).
    /// The BlockDuration Element can be useful at the end of a Track to define the duration of the last frame (as there is no subsequent Block available),
    /// or when there is a break in a track like for subtitle tracks.
    /// BlockDuration **MUST** be set (minOccurs=1) if the associated TrackEntry stores a DefaultDuration value.
    /// When not written and with no DefaultDuration, the value is assumed to be the difference between the timestamp
    /// of this Block and the timestamp of the next Block in "display" order (not coding order).
    name = BlockDuration, original_name = "BlockDuration", id = 0x9B, variant = Unsigned;
    /// This frame is referenced and has the specified cache priority.
    /// In cache only a frame of the same or higher priority can replace this frame. A value of 0 means the frame is not referenced.
    name = ReferencePriority, original_name = "ReferencePriority", id = 0xFA, variant = Unsigned;
    /// A timestamp value, relative to the timestamp of the Block in this BlockGroup, expressed in Track Ticks; see (#timestamp-ticks).
    /// This is used to reference other frames necessary to decode this frame.
    /// The relative value **SHOULD** correspond to a valid `Block` this `Block` depends on.
    /// Historically Matroska Writer didn't write the actual `Block(s)` this `Block` depends on, but *some* `Block` in the past.
    /// The value "0" **MAY** also be used to signify this `Block` cannot be decoded on its own, but without knownledge of which `Block` is necessary. In this case, other `ReferenceBlock` **MUST NOT** be found in the same `BlockGroup`.
    /// If the `BlockGroup` doesn't have any `ReferenceBlock` element, then the `Block` it contains can be decoded without using any other `Block` data.
    name = ReferenceBlock, original_name = "ReferenceBlock", id = 0xFB, variant = Signed;
    /// The Segment Position of the data that would otherwise be in position of the virtual block.
    name = ReferenceVirtual, original_name = "ReferenceVirtual", id = 0xFD, variant = Signed;
    /// The new codec state to use. Data interpretation is private to the codec.
    /// This information **SHOULD** always be referenced by a seek entry.
    name = CodecState, original_name = "CodecState", id = 0xA4, variant = Binary;
    /// Duration of the silent data added to the Block, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks)
    /// (padding at the end of the Block for positive value, at the beginning of the Block for negative value).
    /// The duration of DiscardPadding is not calculated in the duration of the TrackEntry and **SHOULD** be discarded during playback.
    name = DiscardPadding, original_name = "DiscardPadding", id = 0x75A2, variant = Signed;
    /// Contains slices description.
    name = Slices, original_name = "Slices", id = 0x8E, variant = Master;
    /// Contains extra time information about the data contained in the Block.
    /// Being able to interpret this Element is not **REQUIRED** for playback.
    name = TimeSlice, original_name = "TimeSlice", id = 0xE8, variant = Master;
    /// The reverse number of the frame in the lace (0 is the last frame, 1 is the next to last, etc).
    /// Being able to interpret this Element is not **REQUIRED** for playback.
    name = LaceNumber, original_name = "LaceNumber", id = 0xCC, variant = Unsigned;
    /// The number of the frame to generate from this lace with this delay
    /// (allow you to generate many frames from the same Block/Frame).
    name = FrameNumber, original_name = "FrameNumber", id = 0xCD, variant = Unsigned;
    /// The ID of the BlockAdditional Element (0 is the main Block).
    name = BlockAdditionId, original_name = "BlockAdditionID", id = 0xCB, variant = Unsigned;
    /// The delay to apply to the Element, expressed in Track Ticks; see (#timestamp-ticks).
    name = Delay, original_name = "Delay", id = 0xCE, variant = Unsigned;
    /// The duration to apply to the Element, expressed in Track Ticks; see (#timestamp-ticks).
    name = SliceDuration, original_name = "SliceDuration", id = 0xCF, variant = Unsigned;
    /// Contains information about the last reference frame. See [@?DivXTrickTrack].
    name = ReferenceFrame, original_name = "ReferenceFrame", id = 0xC8, variant = Master;
    /// The relative offset, in bytes, from the previous BlockGroup element for this Smooth FF/RW video track to the containing BlockGroup element. See [@?DivXTrickTrack].
    name = ReferenceOffset, original_name = "ReferenceOffset", id = 0xC9, variant = Unsigned;
    /// The timestamp of the BlockGroup pointed to by ReferenceOffset, expressed in Track Ticks; see (#timestamp-ticks). See [@?DivXTrickTrack].
    name = ReferenceTimestamp, original_name = "ReferenceTimestamp", id = 0xCA, variant = Unsigned;
    /// Similar to SimpleBlock, see (#simpleblock-structure),
    /// but the data inside the Block are Transformed (encrypt and/or signed).
    name = EncryptedBlock, original_name = "EncryptedBlock", id = 0xAF, variant = Binary;
    /// A Top-Level Element of information with many tracks described.
    name = Tracks, original_name = "Tracks", id = 0x1654AE6B, variant = Master;
    /// Describes a track with all Elements.
    name = TrackEntry, original_name = "TrackEntry", id = 0xAE, variant = Master;
    /// The track number as used in the Block Header (using more than 127 tracks is not encouraged,
    /// though the design allows an unlimited number).
    name = TrackNumber, original_name = "TrackNumber", id = 0xD7, variant = Unsigned;
    /// A unique ID to identify the Track.
    name = TrackUid, original_name = "TrackUID", id = 0x73C5, variant = Unsigned;
    /// The `TrackType` defines the type of each frame found in the Track.
    /// The value **SHOULD** be stored on 1 octet.
    name = TrackType, original_name = "TrackType", id = 0x83, variant = Unsigned;
    /// Set to 1 if the track is usable. It is possible to turn a not usable track into a usable track using chapter codecs or control tracks.
    name = FlagEnabled, original_name = "FlagEnabled", id = 0xB9, variant = Unsigned;
    /// Set if that track (audio, video or subs) **SHOULD** be eligible for automatic selection by the player; see (#default-track-selection) for more details.
    name = FlagDefault, original_name = "FlagDefault", id = 0x88, variant = Unsigned;
    /// Applies only to subtitles. Set if that track **SHOULD** be eligible for automatic selection by the player if it matches the user's language preference,
    /// even if the user's preferences would normally not enable subtitles with the selected audio track;
    /// this can be used for tracks containing only translations of foreign-language audio or onscreen text.
    /// See (#default-track-selection) for more details.
    name = FlagForced, original_name = "FlagForced", id = 0x55AA, variant = Unsigned;
    /// Set to 1 if that track is suitable for users with hearing impairments, set to 0 if it is unsuitable for users with hearing impairments.
    name = FlagHearingImpaired, original_name = "FlagHearingImpaired", id = 0x55AB, variant = Unsigned;
    /// Set to 1 if that track is suitable for users with visual impairments, set to 0 if it is unsuitable for users with visual impairments.
    name = FlagVisualImpaired, original_name = "FlagVisualImpaired", id = 0x55AC, variant = Unsigned;
    /// Set to 1 if that track contains textual descriptions of video content, set to 0 if that track does not contain textual descriptions of video content.
    name = FlagTextDescriptions, original_name = "FlagTextDescriptions", id = 0x55AD, variant = Unsigned;
    /// Set to 1 if that track is in the content's original language, set to 0 if it is a translation.
    name = FlagOriginal, original_name = "FlagOriginal", id = 0x55AE, variant = Unsigned;
    /// Set to 1 if that track contains commentary, set to 0 if it does not contain commentary.
    name = FlagCommentary, original_name = "FlagCommentary", id = 0x55AF, variant = Unsigned;
    /// Set to 1 if the track **MAY** contain blocks using lacing. When set to 0 all blocks **MUST** have their lacing flags set to No lacing; see (#block-lacing) on Block Lacing.
    name = FlagLacing, original_name = "FlagLacing", id = 0x9C, variant = Unsigned;
    /// The minimum number of frames a player **SHOULD** be able to cache during playback.
    /// If set to 0, the reference pseudo-cache system is not used.
    name = MinCache, original_name = "MinCache", id = 0x6DE7, variant = Unsigned;
    /// The maximum cache size necessary to store referenced frames in and the current frame.
    /// 0 means no cache is needed.
    name = MaxCache, original_name = "MaxCache", id = 0x6DF8, variant = Unsigned;
    /// Number of nanoseconds per frame, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks)
    /// (frame in the Matroska sense -- one Element put into a (Simple)Block).
    name = DefaultDuration, original_name = "DefaultDuration", id = 0x23E383, variant = Unsigned;
    /// The period between two successive fields at the output of the decoding process, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    /// see (#defaultdecodedfieldduration) for more information
    name = DefaultDecodedFieldDuration, original_name = "DefaultDecodedFieldDuration", id = 0x234E7A, variant = Unsigned;
    /// The scale to apply on this track to work at normal speed in relation with other tracks
    /// (mostly used to adjust video speed when the audio length differs).
    name = TrackTimestampScale, original_name = "TrackTimestampScale", id = 0x23314F, variant = Float;
    /// A value to add to the Block's Timestamp, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    /// This can be used to adjust the playback offset of a track.
    name = TrackOffset, original_name = "TrackOffset", id = 0x537F, variant = Signed;
    /// The maximum value of BlockAddID ((#blockaddid-element)).
    /// A value 0 means there is no BlockAdditions ((#blockadditions-element)) for this track.
    name = MaxBlockAdditionId, original_name = "MaxBlockAdditionID", id = 0x55EE, variant = Unsigned;
    /// Contains elements that extend the track format, by adding content either to each frame,
    /// with BlockAddID ((#blockaddid-element)), or to the track as a whole
    /// with BlockAddIDExtraData.
    name = BlockAdditionMapping, original_name = "BlockAdditionMapping", id = 0x41E4, variant = Master;
    /// If the track format extension needs content beside frames,
    /// the value refers to the BlockAddID ((#blockaddid-element)), value being described.
    /// To keep MaxBlockAdditionID as low as possible, small values **SHOULD** be used.
    name = BlockAddIdValue, original_name = "BlockAddIDValue", id = 0x41F0, variant = Unsigned;
    /// A human-friendly name describing the type of BlockAdditional data,
    /// as defined by the associated Block Additional Mapping.
    name = BlockAddIdName, original_name = "BlockAddIDName", id = 0x41A4, variant = String;
    /// Stores the registered identifier of the Block Additional Mapping
    /// to define how the BlockAdditional data should be handled.
    /// If BlockAddIDType is 0, the BlockAddIDValue and corresponding BlockAddID values **MUST** be 1.
    name = BlockAddIdType, original_name = "BlockAddIDType", id = 0x41E7, variant = Unsigned;
    /// Extra binary data that the BlockAddIDType can use to interpret the BlockAdditional data.
    /// The interpretation of the binary data depends on the BlockAddIDType value and the corresponding Block Additional Mapping.
    name = BlockAddIdExtraData, original_name = "BlockAddIDExtraData", id = 0x41ED, variant = Binary;
    /// A human-readable track name.
    name = Name, original_name = "Name", id = 0x536E, variant = Utf8;
    /// Specifies the language of the track in the Matroska languages form;
    /// see (#language-codes) on language codes.
    /// This Element **MUST** be ignored if the LanguageBCP47 Element is used in the same TrackEntry.
    name = Language, original_name = "Language", id = 0x22B59C, variant = String;
    /// Specifies the language of the track according to [@!BCP47]
    /// and using the IANA Language Subtag Registry [@!IANALangRegistry].
    /// If this Element is used, then any Language Elements used in the same TrackEntry **MUST** be ignored.
    name = LanguageBcp47, original_name = "LanguageBCP47", id = 0x22B59D, variant = String;
    /// An ID corresponding to the codec,
    /// see [@!MatroskaCodec] for more info.
    name = CodecId, original_name = "CodecID", id = 0x86, variant = String;
    /// Private data only known to the codec.
    name = CodecPrivate, original_name = "CodecPrivate", id = 0x63A2, variant = Binary;
    /// A human-readable string specifying the codec.
    name = CodecName, original_name = "CodecName", id = 0x258688, variant = Utf8;
    /// The UID of an attachment that is used by this codec.
    /// The value **MUST** match the `FileUID` value of an attachment found in this Segment.
    name = AttachmentLink, original_name = "AttachmentLink", id = 0x7446, variant = Unsigned;
    /// A string describing the encoding setting used.
    name = CodecSettings, original_name = "CodecSettings", id = 0x3A9697, variant = Utf8;
    /// A URL to find information about the codec used.
    name = CodecInfoUrl, original_name = "CodecInfoURL", id = 0x3B4040, variant = String;
    /// A URL to download about the codec used.
    name = CodecDownloadUrl, original_name = "CodecDownloadURL", id = 0x26B240, variant = String;
    /// Set to 1 if the codec can decode potentially damaged data.
    name = CodecDecodeAll, original_name = "CodecDecodeAll", id = 0xAA, variant = Unsigned;
    /// Specify that this track is an overlay track for the Track specified (in the u-integer).
    /// That means when this track has a gap, see (#silenttracks-element) on SilentTracks,
    /// the overlay track **SHOULD** be used instead. The order of multiple TrackOverlay matters, the first one is the one that **SHOULD** be used.
    /// If not found it **SHOULD** be the second, etc.
    name = TrackOverlay, original_name = "TrackOverlay", id = 0x6FAB, variant = Unsigned;
    /// CodecDelay is The codec-built-in delay, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    /// It represents the amount of codec samples that will be discarded by the decoder during playback.
    /// This timestamp value **MUST** be subtracted from each frame timestamp in order to get the timestamp that will be actually played.
    /// The value **SHOULD** be small so the muxing of tracks with the same actual timestamp are in the same Cluster.
    name = CodecDelay, original_name = "CodecDelay", id = 0x56AA, variant = Unsigned;
    /// After a discontinuity, SeekPreRoll is the duration of the data
    /// the decoder **MUST** decode before the decoded data is valid, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    name = SeekPreRoll, original_name = "SeekPreRoll", id = 0x56BB, variant = Unsigned;
    /// The mapping between this `TrackEntry` and a track value in the given Chapter Codec.
    /// Chapter Codec may need to address content in specific track, but they may not know of the way to identify tracks in Matroska.
    /// This element and its child elements add a way to map the internal tracks known to the Chapter Codec to the track IDs in Matroska.
    /// This allows remuxing a file with Chapter Codec without changing the content of the codec data, just the track mapping.
    name = TrackTranslate, original_name = "TrackTranslate", id = 0x6624, variant = Master;
    /// The binary value used to represent this `TrackEntry` in the chapter codec data.
    /// The format depends on the `ChapProcessCodecID` used; see (#chapprocesscodecid-element).
    name = TrackTranslateTrackId, original_name = "TrackTranslateTrackID", id = 0x66A5, variant = Binary;
    /// This `TrackTranslate` applies to this chapter codec of the given chapter edition(s); see (#chapprocesscodecid-element).
    name = TrackTranslateCodec, original_name = "TrackTranslateCodec", id = 0x66BF, variant = Unsigned;
    /// Specify a chapter edition UID on which this `TrackTranslate` applies.
    /// When no `TrackTranslateEditionUID` is specified in the `TrackTranslate`, the `TrackTranslate` applies to all chapter editions found in the Segment using the given `TrackTranslateCodec`.
    name = TrackTranslateEditionUid, original_name = "TrackTranslateEditionUID", id = 0x66FC, variant = Unsigned;
    /// Video settings.
    name = Video, original_name = "Video", id = 0xE0, variant = Master;
    /// Specify whether the video frames in this track are interlaced or not.
    name = FlagInterlaced, original_name = "FlagInterlaced", id = 0x9A, variant = Unsigned;
    /// Specify the field ordering of video frames in this track.
    /// If FlagInterlaced is not set to 1, this Element **MUST** be ignored.
    name = FieldOrder, original_name = "FieldOrder", id = 0x9D, variant = Unsigned;
    /// Stereo-3D video mode. There are some more details in (#multi-planar-and-3d-videos).
    name = StereoMode, original_name = "StereoMode", id = 0x53B8, variant = Unsigned;
    /// Indicate whether the BlockAdditional Element with BlockAddID of "1" contains Alpha data, as defined by to the Codec Mapping for the `CodecID`.
    /// Undefined values **SHOULD NOT** be used as the behavior of known implementations is different (considered either as 0 or 1).
    name = AlphaMode, original_name = "AlphaMode", id = 0x53C0, variant = Unsigned;
    /// Bogus StereoMode value used in old versions of libmatroska.
    /// This Element **MUST NOT** be used. It was an incorrect value used in libmatroska up to 0.9.0.
    name = OldStereoMode, original_name = "OldStereoMode", id = 0x53B9, variant = Unsigned;
    /// Width of the encoded video frames in pixels.
    name = PixelWidth, original_name = "PixelWidth", id = 0xB0, variant = Unsigned;
    /// Height of the encoded video frames in pixels.
    name = PixelHeight, original_name = "PixelHeight", id = 0xBA, variant = Unsigned;
    /// The number of video pixels to remove at the bottom of the image.
    name = PixelCropBottom, original_name = "PixelCropBottom", id = 0x54AA, variant = Unsigned;
    /// The number of video pixels to remove at the top of the image.
    name = PixelCropTop, original_name = "PixelCropTop", id = 0x54BB, variant = Unsigned;
    /// The number of video pixels to remove on the left of the image.
    name = PixelCropLeft, original_name = "PixelCropLeft", id = 0x54CC, variant = Unsigned;
    /// The number of video pixels to remove on the right of the image.
    name = PixelCropRight, original_name = "PixelCropRight", id = 0x54DD, variant = Unsigned;
    /// Width of the video frames to display. Applies to the video frame after cropping (PixelCrop* Elements).
    /// If the DisplayUnit of the same TrackEntry is 0, then the default value for DisplayWidth is equal to
    /// PixelWidth - PixelCropLeft - PixelCropRight, else there is no default value.
    name = DisplayWidth, original_name = "DisplayWidth", id = 0x54B0, variant = Unsigned;
    /// Height of the video frames to display. Applies to the video frame after cropping (PixelCrop* Elements).
    /// If the DisplayUnit of the same TrackEntry is 0, then the default value for DisplayHeight is equal to
    /// PixelHeight - PixelCropTop - PixelCropBottom, else there is no default value.
    name = DisplayHeight, original_name = "DisplayHeight", id = 0x54BA, variant = Unsigned;
    /// How DisplayWidth & DisplayHeight are interpreted.
    name = DisplayUnit, original_name = "DisplayUnit", id = 0x54B2, variant = Unsigned;
    /// Specify the possible modifications to the aspect ratio.
    name = AspectRatioType, original_name = "AspectRatioType", id = 0x54B3, variant = Unsigned;
    /// Specify the uncompressed pixel format used for the Track's data as a FourCC.
    /// This value is similar in scope to the biCompression value of AVI's `BITMAPINFO` [@?AVIFormat]. See the YUV video formats [@?FourCC-YUV] and RGB video formats [@?FourCC-RGB] for common values.
    /// UncompressedFourCC **MUST** be set (minOccurs=1) in TrackEntry, when the CodecID Element of the TrackEntry is set to "V_UNCOMPRESSED".
    name = UncompressedFourCc, original_name = "UncompressedFourCC", id = 0x2EB524, variant = Binary;
    /// Gamma Value.
    name = GammaValue, original_name = "GammaValue", id = 0x2FB523, variant = Float;
    /// Number of frames per second. This value is Informational only. It is intended for constant frame rate streams, and **SHOULD NOT** be used for a variable frame rate TrackEntry.
    name = FrameRate, original_name = "FrameRate", id = 0x2383E3, variant = Float;
    /// Settings describing the colour format.
    name = Colour, original_name = "Colour", id = 0x55B0, variant = Master;
    /// The Matrix Coefficients of the video used to derive luma and chroma values from red, green, and blue color primaries.
    /// For clarity, the value and meanings for MatrixCoefficients are adopted from Table 4 of ISO/IEC 23001-8:2016 or ITU-T H.273.
    name = MatrixCoefficients, original_name = "MatrixCoefficients", id = 0x55B1, variant = Unsigned;
    /// Number of decoded bits per channel. A value of 0 indicates that the BitsPerChannel is unspecified.
    name = BitsPerChannel, original_name = "BitsPerChannel", id = 0x55B2, variant = Unsigned;
    /// The amount of pixels to remove in the Cr and Cb channels for every pixel not removed horizontally.
    /// Example: For video with 4:2:0 chroma subsampling, the ChromaSubsamplingHorz **SHOULD** be set to 1.
    name = ChromaSubsamplingHorz, original_name = "ChromaSubsamplingHorz", id = 0x55B3, variant = Unsigned;
    /// The amount of pixels to remove in the Cr and Cb channels for every pixel not removed vertically.
    /// Example: For video with 4:2:0 chroma subsampling, the ChromaSubsamplingVert **SHOULD** be set to 1.
    name = ChromaSubsamplingVert, original_name = "ChromaSubsamplingVert", id = 0x55B4, variant = Unsigned;
    /// The amount of pixels to remove in the Cb channel for every pixel not removed horizontally.
    /// This is additive with ChromaSubsamplingHorz. Example: For video with 4:2:1 chroma subsampling,
    /// the ChromaSubsamplingHorz **SHOULD** be set to 1 and CbSubsamplingHorz **SHOULD** be set to 1.
    name = CbSubsamplingHorz, original_name = "CbSubsamplingHorz", id = 0x55B5, variant = Unsigned;
    /// The amount of pixels to remove in the Cb channel for every pixel not removed vertically.
    /// This is additive with ChromaSubsamplingVert.
    name = CbSubsamplingVert, original_name = "CbSubsamplingVert", id = 0x55B6, variant = Unsigned;
    /// How chroma is subsampled horizontally.
    name = ChromaSitingHorz, original_name = "ChromaSitingHorz", id = 0x55B7, variant = Unsigned;
    /// How chroma is subsampled vertically.
    name = ChromaSitingVert, original_name = "ChromaSitingVert", id = 0x55B8, variant = Unsigned;
    /// Clipping of the color ranges.
    name = Range, original_name = "Range", id = 0x55B9, variant = Unsigned;
    /// The transfer characteristics of the video. For clarity,
    /// the value and meanings for TransferCharacteristics are adopted from Table 3 of ISO/IEC 23091-4 or ITU-T H.273.
    name = TransferCharacteristics, original_name = "TransferCharacteristics", id = 0x55BA, variant = Unsigned;
    /// The colour primaries of the video. For clarity,
    /// the value and meanings for Primaries are adopted from Table 2 of ISO/IEC 23091-4 or ITU-T H.273.
    name = Primaries, original_name = "Primaries", id = 0x55BB, variant = Unsigned;
    /// Maximum brightness of a single pixel (Maximum Content Light Level)
    /// in candelas per square meter (cd/m^2^).
    name = MaxCll, original_name = "MaxCLL", id = 0x55BC, variant = Unsigned;
    /// Maximum brightness of a single full frame (Maximum Frame-Average Light Level)
    /// in candelas per square meter (cd/m^2^).
    name = MaxFall, original_name = "MaxFALL", id = 0x55BD, variant = Unsigned;
    /// SMPTE 2086 mastering data.
    name = MasteringMetadata, original_name = "MasteringMetadata", id = 0x55D0, variant = Master;
    /// Red X chromaticity coordinate, as defined by [@!CIE-1931].
    name = PrimaryRChromaticityX, original_name = "PrimaryRChromaticityX", id = 0x55D1, variant = Float;
    /// Red Y chromaticity coordinate, as defined by [@!CIE-1931].
    name = PrimaryRChromaticityY, original_name = "PrimaryRChromaticityY", id = 0x55D2, variant = Float;
    /// Green X chromaticity coordinate, as defined by [@!CIE-1931].
    name = PrimaryGChromaticityX, original_name = "PrimaryGChromaticityX", id = 0x55D3, variant = Float;
    /// Green Y chromaticity coordinate, as defined by [@!CIE-1931].
    name = PrimaryGChromaticityY, original_name = "PrimaryGChromaticityY", id = 0x55D4, variant = Float;
    /// Blue X chromaticity coordinate, as defined by [@!CIE-1931].
    name = PrimaryBChromaticityX, original_name = "PrimaryBChromaticityX", id = 0x55D5, variant = Float;
    /// Blue Y chromaticity coordinate, as defined by [@!CIE-1931].
    name = PrimaryBChromaticityY, original_name = "PrimaryBChromaticityY", id = 0x55D6, variant = Float;
    /// White X chromaticity coordinate, as defined by [@!CIE-1931].
    name = WhitePointChromaticityX, original_name = "WhitePointChromaticityX", id = 0x55D7, variant = Float;
    /// White Y chromaticity coordinate, as defined by [@!CIE-1931].
    name = WhitePointChromaticityY, original_name = "WhitePointChromaticityY", id = 0x55D8, variant = Float;
    /// Maximum luminance. Represented in candelas per square meter (cd/m^2^).
    name = LuminanceMax, original_name = "LuminanceMax", id = 0x55D9, variant = Float;
    /// Minimum luminance. Represented in candelas per square meter (cd/m^2^).
    name = LuminanceMin, original_name = "LuminanceMin", id = 0x55DA, variant = Float;
    /// Describes the video projection details. Used to render spherical, VR videos or flipping videos horizontally/vertically.
    name = Projection, original_name = "Projection", id = 0x7670, variant = Master;
    /// Describes the projection used for this video track.
    name = ProjectionType, original_name = "ProjectionType", id = 0x7671, variant = Unsigned;
    /// Private data that only applies to a specific projection.
    /// *  If `ProjectionType` equals 0 (Rectangular),
    ///      then this element must not be present.
    /// *  If `ProjectionType` equals 1 (Equirectangular), then this element must be present and contain the same binary data that would be stored inside
    ///       an ISOBMFF Equirectangular Projection Box ('equi').
    /// *  If `ProjectionType` equals 2 (Cubemap), then this element must be present and contain the same binary data that would be stored
    ///       inside an ISOBMFF Cubemap Projection Box ('cbmp').
    /// *  If `ProjectionType` equals 3 (Mesh), then this element must be present and contain the same binary data that would be stored inside
    ///        an ISOBMFF Mesh Projection Box ('mshp').
    /// ISOBMFF box size and fourcc fields are not included in the binary data,
    /// but the FullBox version and flag fields are. This is to avoid
    /// redundant framing information while preserving versioning and semantics between the two container formats.
    name = ProjectionPrivate, original_name = "ProjectionPrivate", id = 0x7672, variant = Binary;
    /// Specifies a yaw rotation to the projection.
    /// Value represents a clockwise rotation, in degrees, around the up vector. This rotation must be applied
    /// before any `ProjectionPosePitch` or `ProjectionPoseRoll` rotations.
    /// The value of this element **MUST** be in the -180 to 180 degree range, both included.
    /// Setting `ProjectionPoseYaw` to 180 or -180 degrees, with the `ProjectionPoseRoll` and `ProjectionPosePitch` set to 0 degrees flips the image horizontally.
    name = ProjectionPoseYaw, original_name = "ProjectionPoseYaw", id = 0x7673, variant = Float;
    /// Specifies a pitch rotation to the projection.
    /// Value represents a counter-clockwise rotation, in degrees, around the right vector. This rotation must be applied
    /// after the `ProjectionPoseYaw` rotation and before the `ProjectionPoseRoll` rotation.
    /// The value of this element **MUST** be in the -90 to 90 degree range, both included.
    name = ProjectionPosePitch, original_name = "ProjectionPosePitch", id = 0x7674, variant = Float;
    /// Specifies a roll rotation to the projection.
    /// Value represents a counter-clockwise rotation, in degrees, around the forward vector. This rotation must be applied
    /// after the `ProjectionPoseYaw` and `ProjectionPosePitch` rotations.
    /// The value of this element **MUST** be in the -180 to 180 degree range, both included.
    /// Setting `ProjectionPoseRoll` to 180 or -180 degrees, the `ProjectionPoseYaw` to 180 or -180 degrees with `ProjectionPosePitch` set to 0 degrees flips the image vertically.
    /// Setting `ProjectionPoseRoll` to 180 or -180 degrees, with the `ProjectionPoseYaw` and `ProjectionPosePitch` set to 0 degrees flips the image horizontally and vertically.
    name = ProjectionPoseRoll, original_name = "ProjectionPoseRoll", id = 0x7675, variant = Float;
    /// Audio settings.
    name = Audio, original_name = "Audio", id = 0xE1, variant = Master;
    /// Sampling frequency in Hz.
    name = SamplingFrequency, original_name = "SamplingFrequency", id = 0xB5, variant = Float;
    /// Real output sampling frequency in Hz (used for SBR techniques).
    /// The default value for OutputSamplingFrequency of the same TrackEntry is equal to the SamplingFrequency.
    name = OutputSamplingFrequency, original_name = "OutputSamplingFrequency", id = 0x78B5, variant = Float;
    /// Numbers of channels in the track.
    name = Channels, original_name = "Channels", id = 0x9F, variant = Unsigned;
    /// Table of horizontal angles for each successive channel.
    name = ChannelPositions, original_name = "ChannelPositions", id = 0x7D7B, variant = Binary;
    /// Bits per sample, mostly used for PCM.
    name = BitDepth, original_name = "BitDepth", id = 0x6264, variant = Unsigned;
    /// Operation that needs to be applied on tracks to create this virtual track.
    /// For more details look at (#track-operation).
    name = TrackOperation, original_name = "TrackOperation", id = 0xE2, variant = Master;
    /// Contains the list of all video plane tracks that need to be combined to create this 3D track
    name = TrackCombinePlanes, original_name = "TrackCombinePlanes", id = 0xE3, variant = Master;
    /// Contains a video plane track that need to be combined to create this 3D track
    name = TrackPlane, original_name = "TrackPlane", id = 0xE4, variant = Master;
    /// The trackUID number of the track representing the plane.
    name = TrackPlaneUid, original_name = "TrackPlaneUID", id = 0xE5, variant = Unsigned;
    /// The kind of plane this track corresponds to.
    name = TrackPlaneType, original_name = "TrackPlaneType", id = 0xE6, variant = Unsigned;
    /// Contains the list of all tracks whose Blocks need to be combined to create this virtual track
    name = TrackJoinBlocks, original_name = "TrackJoinBlocks", id = 0xE9, variant = Master;
    /// The trackUID number of a track whose blocks are used to create this virtual track.
    name = TrackJoinUid, original_name = "TrackJoinUID", id = 0xED, variant = Unsigned;
    /// The TrackUID of the Smooth FF/RW video in the paired EBML structure corresponding to this video track. See [@?DivXTrickTrack].
    name = TrickTrackUid, original_name = "TrickTrackUID", id = 0xC0, variant = Unsigned;
    /// The SegmentUID of the Segment containing the track identified by TrickTrackUID. See [@?DivXTrickTrack].
    name = TrickTrackSegmentUid, original_name = "TrickTrackSegmentUID", id = 0xC1, variant = Binary;
    /// Set to 1 if this video track is a Smooth FF/RW track. If set to 1, MasterTrackUID and MasterTrackSegUID should must be present and BlockGroups for this track must contain ReferenceFrame structures.
    /// Otherwise, TrickTrackUID and TrickTrackSegUID must be present if this track has a corresponding Smooth FF/RW track. See [@?DivXTrickTrack].
    name = TrickTrackFlag, original_name = "TrickTrackFlag", id = 0xC6, variant = Unsigned;
    /// The TrackUID of the video track in the paired EBML structure that corresponds to this Smooth FF/RW track. See [@?DivXTrickTrack].
    name = TrickMasterTrackUid, original_name = "TrickMasterTrackUID", id = 0xC7, variant = Unsigned;
    /// The SegmentUID of the Segment containing the track identified by MasterTrackUID. See [@?DivXTrickTrack].
    name = TrickMasterTrackSegmentUid, original_name = "TrickMasterTrackSegmentUID", id = 0xC4, variant = Binary;
    /// Settings for several content encoding mechanisms like compression or encryption.
    name = ContentEncodings, original_name = "ContentEncodings", id = 0x6D80, variant = Master;
    /// Settings for one content encoding like compression or encryption.
    name = ContentEncoding, original_name = "ContentEncoding", id = 0x6240, variant = Master;
    /// Tell in which order to apply each `ContentEncoding` of the `ContentEncodings`.
    /// The decoder/demuxer **MUST** start with the `ContentEncoding` with the highest `ContentEncodingOrder` and work its way down to the `ContentEncoding` with the lowest `ContentEncodingOrder`.
    /// This value **MUST** be unique over for each `ContentEncoding` found in the `ContentEncodings` of this `TrackEntry`.
    name = ContentEncodingOrder, original_name = "ContentEncodingOrder", id = 0x5031, variant = Unsigned;
    /// A bit field that describes which Elements have been modified in this way.
    /// Values (big-endian) can be OR'ed.
    name = ContentEncodingScope, original_name = "ContentEncodingScope", id = 0x5032, variant = Unsigned;
    /// A value describing what kind of transformation is applied.
    name = ContentEncodingType, original_name = "ContentEncodingType", id = 0x5033, variant = Unsigned;
    /// Settings describing the compression used.
    /// This Element **MUST** be present if the value of ContentEncodingType is 0 and absent otherwise.
    /// Each block **MUST** be decompressable even if no previous block is available in order not to prevent seeking.
    name = ContentCompression, original_name = "ContentCompression", id = 0x5034, variant = Master;
    /// The compression algorithm used.
    /// Compression method "1" (bzlib) and "2" (lzo1x) are lacking proper documentation on the format which limits implementation possibilities.
    /// Due to licensing conflicts on commonly available libraries compression methods "2" (lzo1x) does not offer widespread interoperability.
    /// Decoding implementations **MAY** support methods "1" and "2" as possible. The use of these compression methods **SHOULD NOT** be used as a default.
    name = ContentCompAlgo, original_name = "ContentCompAlgo", id = 0x4254, variant = Unsigned;
    /// Settings that might be needed by the decompressor. For Header Stripping (`ContentCompAlgo`=3),
    /// the bytes that were removed from the beginning of each frames of the track.
    name = ContentCompSettings, original_name = "ContentCompSettings", id = 0x4255, variant = Binary;
    /// Settings describing the encryption used.
    /// This Element **MUST** be present if the value of `ContentEncodingType` is 1 (encryption) and **MUST** be ignored otherwise.
    name = ContentEncryption, original_name = "ContentEncryption", id = 0x5035, variant = Master;
    /// The encryption algorithm used.
    name = ContentEncAlgo, original_name = "ContentEncAlgo", id = 0x47E1, variant = Unsigned;
    /// For public key algorithms this is the ID of the public key the the data was encrypted with.
    name = ContentEncKeyId, original_name = "ContentEncKeyID", id = 0x47E2, variant = Binary;
    /// Settings describing the encryption algorithm used.
    /// ContentEncAESSettings **MUST NOT** be set (maxOccurs=0) if ContentEncAlgo is not AES (5).
    name = ContentEncAesSettings, original_name = "ContentEncAESSettings", id = 0x47E7, variant = Master;
    /// The AES cipher mode used in the encryption.
    /// AESSettingsCipherMode **MUST NOT** be set (maxOccurs=0) if ContentEncAlgo is not AES (5).
    name = AesSettingsCipherMode, original_name = "AESSettingsCipherMode", id = 0x47E8, variant = Unsigned;
    /// A cryptographic signature of the contents.
    name = ContentSignature, original_name = "ContentSignature", id = 0x47E3, variant = Binary;
    /// This is the ID of the private key the data was signed with.
    name = ContentSigKeyId, original_name = "ContentSigKeyID", id = 0x47E4, variant = Binary;
    /// The algorithm used for the signature.
    name = ContentSigAlgo, original_name = "ContentSigAlgo", id = 0x47E5, variant = Unsigned;
    /// The hash algorithm used for the signature.
    name = ContentSigHashAlgo, original_name = "ContentSigHashAlgo", id = 0x47E6, variant = Unsigned;
    /// A Top-Level Element to speed seeking access.
    /// All entries are local to the Segment.
    /// This Element **SHOULD** be set when the Segment is not transmitted as a live stream (see #livestreaming).
    name = Cues, original_name = "Cues", id = 0x1C53BB6B, variant = Master;
    /// Contains all information relative to a seek point in the Segment.
    name = CuePoint, original_name = "CuePoint", id = 0xBB, variant = Master;
    /// Absolute timestamp of the seek point, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    name = CueTime, original_name = "CueTime", id = 0xB3, variant = Unsigned;
    /// Contain positions for different tracks corresponding to the timestamp.
    name = CueTrackPositions, original_name = "CueTrackPositions", id = 0xB7, variant = Master;
    /// The track for which a position is given.
    name = CueTrack, original_name = "CueTrack", id = 0xF7, variant = Unsigned;
    /// The Segment Position ((#segment-position)) of the Cluster containing the associated Block.
    name = CueClusterPosition, original_name = "CueClusterPosition", id = 0xF1, variant = Unsigned;
    /// The relative position inside the Cluster of the referenced SimpleBlock or BlockGroup
    /// with 0 being the first possible position for an Element inside that Cluster.
    name = CueRelativePosition, original_name = "CueRelativePosition", id = 0xF0, variant = Unsigned;
    /// The duration of the block, expressed in Segment Ticks which is based on TimestampScale; see (#timestamp-ticks).
    /// If missing, the track's DefaultDuration does not apply and no duration information is available in terms of the cues.
    name = CueDuration, original_name = "CueDuration", id = 0xB2, variant = Unsigned;
    /// Number of the Block in the specified Cluster.
    name = CueBlockNumber, original_name = "CueBlockNumber", id = 0x5378, variant = Unsigned;
    /// The Segment Position ((#segment-position)) of the Codec State corresponding to this Cue Element.
    /// 0 means that the data is taken from the initial Track Entry.
    name = CueCodecState, original_name = "CueCodecState", id = 0xEA, variant = Unsigned;
    /// The Clusters containing the referenced Blocks.
    name = CueReference, original_name = "CueReference", id = 0xDB, variant = Master;
    /// Timestamp of the referenced Block, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    name = CueRefTime, original_name = "CueRefTime", id = 0x96, variant = Unsigned;
    /// The Segment Position of the Cluster containing the referenced Block.
    name = CueRefCluster, original_name = "CueRefCluster", id = 0x97, variant = Unsigned;
    /// Number of the referenced Block of Track X in the specified Cluster.
    name = CueRefNumber, original_name = "CueRefNumber", id = 0x535F, variant = Unsigned;
    /// The Segment Position of the Codec State corresponding to this referenced Element.
    /// 0 means that the data is taken from the initial Track Entry.
    name = CueRefCodecState, original_name = "CueRefCodecState", id = 0xEB, variant = Unsigned;
    /// Contain attached files.
    name = Attachments, original_name = "Attachments", id = 0x1941A469, variant = Master;
    /// An attached file.
    name = AttachedFile, original_name = "AttachedFile", id = 0x61A7, variant = Master;
    /// A human-friendly name for the attached file.
    name = FileDescription, original_name = "FileDescription", id = 0x467E, variant = Utf8;
    /// Filename of the attached file.
    name = FileName, original_name = "FileName", id = 0x466E, variant = Utf8;
    /// MIME type of the file.
    name = FileMimeType, original_name = "FileMimeType", id = 0x4660, variant = String;
    /// The data of the file.
    name = FileData, original_name = "FileData", id = 0x465C, variant = Binary;
    /// Unique ID representing the file, as random as possible.
    name = FileUid, original_name = "FileUID", id = 0x46AE, variant = Unsigned;
    /// A binary value that a track/codec can refer to when the attachment is needed.
    name = FileReferral, original_name = "FileReferral", id = 0x4675, variant = Binary;
    /// The timestamp at which this optimized font attachment comes into context, expressed in Segment Ticks which is based on TimestampScale. See [@?DivXWorldFonts].
    /// This element is reserved for future use and if written **MUST** be the segment start timestamp.
    name = FileUsedStartTime, original_name = "FileUsedStartTime", id = 0x4661, variant = Unsigned;
    /// The timestamp at which this optimized font attachment goes out of context, expressed in Segment Ticks which is based on TimestampScale. See [@?DivXWorldFonts].
    /// This element is reserved for future use and if written **MUST** be the segment end timestamp.
    name = FileUsedEndTime, original_name = "FileUsedEndTime", id = 0x4662, variant = Unsigned;
    /// A system to define basic menus and partition data.
    /// For more detailed information, look at the Chapters explanation in (#chapters).
    name = Chapters, original_name = "Chapters", id = 0x1043A770, variant = Master;
    /// Contains all information about a Segment edition.
    name = EditionEntry, original_name = "EditionEntry", id = 0x45B9, variant = Master;
    /// A unique ID to identify the edition. It's useful for tagging an edition.
    name = EditionUid, original_name = "EditionUID", id = 0x45BC, variant = Unsigned;
    /// Set to 1 if an edition is hidden. Hidden editions **SHOULD NOT** be available to the user interface
    /// (but still to Control Tracks; see (#chapter-flags) on Chapter flags).
    name = EditionFlagHidden, original_name = "EditionFlagHidden", id = 0x45BD, variant = Unsigned;
    /// Set to 1 if the edition **SHOULD** be used as the default one.
    name = EditionFlagDefault, original_name = "EditionFlagDefault", id = 0x45DB, variant = Unsigned;
    /// Set to 1 if the chapters can be defined multiple times and the order to play them is enforced; see (#editionflagordered).
    name = EditionFlagOrdered, original_name = "EditionFlagOrdered", id = 0x45DD, variant = Unsigned;
    /// Contains the atom information to use as the chapter atom (apply to all tracks).
    name = ChapterAtom, original_name = "ChapterAtom", id = 0xB6, variant = Master;
    /// A unique ID to identify the Chapter.
    name = ChapterUid, original_name = "ChapterUID", id = 0x73C4, variant = Unsigned;
    /// A unique string ID to identify the Chapter.
    /// Use for WebVTT cue identifier storage [@!WebVTT].
    name = ChapterStringUid, original_name = "ChapterStringUID", id = 0x5654, variant = Utf8;
    /// Timestamp of the start of Chapter, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    name = ChapterTimeStart, original_name = "ChapterTimeStart", id = 0x91, variant = Unsigned;
    /// Timestamp of the end of Chapter timestamp excluded, expressed in Matroska Ticks -- ie in nanoseconds; see (#timestamp-ticks).
    /// The value **MUST** be greater than or equal to the `ChapterTimeStart` of the same `ChapterAtom`.
    /// The `ChapterTimeEnd` timestamp value being excluded, it **MUST** take in account the duration of
    /// the last frame it includes, especially for the `ChapterAtom` using the last frames of the `Segment`.
    /// ChapterTimeEnd **MUST** be set (minOccurs=1) if the Edition is an ordered edition; see (#editionflagordered), unless it's a `Parent Chapter`; see (#nested-chapters)
    name = ChapterTimeEnd, original_name = "ChapterTimeEnd", id = 0x92, variant = Unsigned;
    /// Set to 1 if a chapter is hidden. Hidden chapters **SHOULD NOT** be available to the user interface
    /// (but still to Control Tracks; see (#chapterflaghidden) on Chapter flags).
    name = ChapterFlagHidden, original_name = "ChapterFlagHidden", id = 0x98, variant = Unsigned;
    /// Set to 1 if the chapter is enabled. It can be enabled/disabled by a Control Track.
    /// When disabled, the movie **SHOULD** skip all the content between the TimeStart and TimeEnd of this chapter; see (#chapter-flags) on Chapter flags.
    name = ChapterFlagEnabled, original_name = "ChapterFlagEnabled", id = 0x4598, variant = Unsigned;
    /// The SegmentUUID of another Segment to play during this chapter (128 bits).
    /// Like the SegmentUUID, it is a Universally Unique IDentifier stored in binary form [@!RFC4122].
    /// The value **MUST NOT** be the `SegmentUUID` value of the `Segment` it belongs to.
    /// ChapterSegmentUUID **MUST** be set (minOccurs=1) if ChapterSegmentEditionUID is used; see (#medium-linking) on medium-linking Segments.
    name = ChapterSegmentUuid, original_name = "ChapterSegmentUUID", id = 0x6E67, variant = Binary;
    /// The EditionUID to play from the Segment linked in ChapterSegmentUUID.
    /// If ChapterSegmentEditionUID is undeclared, then no Edition of the linked Segment is used; see (#medium-linking) on medium-linking Segments.
    name = ChapterSegmentEditionUid, original_name = "ChapterSegmentEditionUID", id = 0x6EBC, variant = Unsigned;
    /// Specify the physical equivalent of this ChapterAtom like "DVD" (60) or "SIDE" (50);
    /// see (#physical-types) for a complete list of values.
    name = ChapterPhysicalEquiv, original_name = "ChapterPhysicalEquiv", id = 0x63C3, variant = Unsigned;
    /// List of tracks on which the chapter applies. If this Element is not present, all tracks apply
    name = ChapterTrack, original_name = "ChapterTrack", id = 0x8F, variant = Master;
    /// UID of the Track to apply this chapter to.
    /// In the absence of a control track, choosing this chapter will select the listed Tracks and deselect unlisted tracks.
    /// Absence of this Element indicates that the Chapter **SHOULD** be applied to any currently used Tracks.
    name = ChapterTrackUid, original_name = "ChapterTrackUID", id = 0x89, variant = Unsigned;
    /// Contains all possible strings to use for the chapter display.
    name = ChapterDisplay, original_name = "ChapterDisplay", id = 0x80, variant = Master;
    /// Contains the string to use as the chapter atom.
    name = ChapString, original_name = "ChapString", id = 0x85, variant = Utf8;
    /// A language corresponding to the string,
    /// in the bibliographic ISO-639-2 form [@!ISO639-2].
    /// This Element **MUST** be ignored if a ChapLanguageBCP47 Element is used within the same ChapterDisplay Element.
    name = ChapLanguage, original_name = "ChapLanguage", id = 0x437C, variant = String;
    /// Specifies a language corresponding to the ChapString in the format defined in [@!BCP47]
    /// and using the IANA Language Subtag Registry [@!IANALangRegistry].
    /// If a ChapLanguageBCP47 Element is used, then any ChapLanguage and ChapCountry Elements used in the same ChapterDisplay **MUST** be ignored.
    name = ChapLanguageBcp47, original_name = "ChapLanguageBCP47", id = 0x437D, variant = String;
    /// A country corresponding to the string, using the same 2 octets country-codes as in Internet domains [@!IANADomains] based on [@!ISO3166-1] alpha-2 codes.
    /// This Element **MUST** be ignored if a ChapLanguageBCP47 Element is used within the same ChapterDisplay Element.
    name = ChapCountry, original_name = "ChapCountry", id = 0x437E, variant = String;
    /// Contains all the commands associated to the Atom.
    name = ChapProcess, original_name = "ChapProcess", id = 0x6944, variant = Master;
    /// Contains the type of the codec used for the processing.
    /// A value of 0 means native Matroska processing (to be defined), a value of 1 means the DVD command set is used; see (#menu-features) on DVD menus.
    /// More codec IDs can be added later.
    name = ChapProcessCodecId, original_name = "ChapProcessCodecID", id = 0x6955, variant = Unsigned;
    /// Some optional data attached to the ChapProcessCodecID information.
    ///     For ChapProcessCodecID = 1, it is the "DVD level" equivalent; see (#menu-features) on DVD menus.
    name = ChapProcessPrivate, original_name = "ChapProcessPrivate", id = 0x450D, variant = Binary;
    /// Contains all the commands associated to the Atom.
    name = ChapProcessCommand, original_name = "ChapProcessCommand", id = 0x6911, variant = Master;
    /// Defines when the process command **SHOULD** be handled
    name = ChapProcessTime, original_name = "ChapProcessTime", id = 0x6922, variant = Unsigned;
    /// Contains the command information.
    /// The data **SHOULD** be interpreted depending on the ChapProcessCodecID value. For ChapProcessCodecID = 1,
    /// the data correspond to the binary DVD cell pre/post commands; see (#menu-features) on DVD menus.
    name = ChapProcessData, original_name = "ChapProcessData", id = 0x6933, variant = Binary;
    /// Element containing metadata describing Tracks, Editions, Chapters, Attachments, or the Segment as a whole.
    /// A list of valid tags can be found in [@!MatroskaTags].
    name = Tags, original_name = "Tags", id = 0x1254C367, variant = Master;
    /// A single metadata descriptor.
    name = Tag, original_name = "Tag", id = 0x7373, variant = Master;
    /// Specifies which other elements the metadata represented by the Tag applies to.
    /// If empty or not present, then the Tag describes everything in the Segment.
    name = Targets, original_name = "Targets", id = 0x63C0, variant = Master;
    /// A number to indicate the logical level of the target.
    name = TargetTypeValue, original_name = "TargetTypeValue", id = 0x68CA, variant = Unsigned;
    /// An informational string that can be used to display the logical level of the target like "ALBUM", "TRACK", "MOVIE", "CHAPTER", etc
    /// ; see Section 6.4 of [@!MatroskaTags].
    name = TargetType, original_name = "TargetType", id = 0x63CA, variant = String;
    /// A unique ID to identify the Track(s) the tags belong to.
    /// If the value is 0 at this level, the tags apply to all tracks in the Segment.
    /// If set to any other value, it **MUST** match the `TrackUID` value of a track found in this Segment.
    name = TagTrackUid, original_name = "TagTrackUID", id = 0x63C5, variant = Unsigned;
    /// A unique ID to identify the EditionEntry(s) the tags belong to.
    /// If the value is 0 at this level, the tags apply to all editions in the Segment.
    /// If set to any other value, it **MUST** match the `EditionUID` value of an edition found in this Segment.
    name = TagEditionUid, original_name = "TagEditionUID", id = 0x63C9, variant = Unsigned;
    /// A unique ID to identify the Chapter(s) the tags belong to.
    /// If the value is 0 at this level, the tags apply to all chapters in the Segment.
    /// If set to any other value, it **MUST** match the `ChapterUID` value of a chapter found in this Segment.
    name = TagChapterUid, original_name = "TagChapterUID", id = 0x63C4, variant = Unsigned;
    /// A unique ID to identify the Attachment(s) the tags belong to.
    /// If the value is 0 at this level, the tags apply to all the attachments in the Segment.
    /// If set to any other value, it **MUST** match the `FileUID` value of an attachment found in this Segment.
    name = TagAttachmentUid, original_name = "TagAttachmentUID", id = 0x63C6, variant = Unsigned;
    /// Contains general information about the target.
    name = SimpleTag, original_name = "SimpleTag", id = 0x67C8, variant = Master;
    /// The name of the Tag that is going to be stored.
    name = TagName, original_name = "TagName", id = 0x45A3, variant = Utf8;
    /// Specifies the language of the tag specified, in the Matroska languages form;
    /// see (#language-codes) on language codes.
    /// This Element **MUST** be ignored if the TagLanguageBCP47 Element is used within the same SimpleTag Element.
    name = TagLanguage, original_name = "TagLanguage", id = 0x447A, variant = String;
    /// Specifies the language used in the TagString according to [@!BCP47]
    /// and using the IANA Language Subtag Registry [@!IANALangRegistry].
    /// If this Element is used, then any TagLanguage Elements used in the same SimpleTag **MUST** be ignored.
    name = TagLanguageBcp47, original_name = "TagLanguageBCP47", id = 0x447B, variant = String;
    /// A boolean value to indicate if this is the default/original language to use for the given tag.
    name = TagDefault, original_name = "TagDefault", id = 0x4484, variant = Unsigned;
    /// A variant of the TagDefault element with a bogus Element ID; see (#tagdefault-element).
    name = TagDefaultBogus, original_name = "TagDefaultBogus", id = 0x44B4, variant = Unsigned;
    /// The value of the Tag.
    name = TagString, original_name = "TagString", id = 0x4487, variant = Utf8;
    /// The values of the Tag, if it is binary. Note that this cannot be used in the same SimpleTag as TagString.
    name = TagBinary, original_name = "TagBinary", id = 0x4485, variant = Binary;
}
