// DO NOT EDIT! This file is auto-generated by build.rs.
// Instead, update ebml.xml and ebml_matroska.xml
use crate::ebml::ebml_enumerations;
ebml_enumerations! {
    ChapterTranslateCodec {
        MatroskaScript = 0,
        DvdMenu = 1,
    };
    TrackType {
        Video = 1,
        Audio = 2,
        Complex = 3,
        Logo = 16,
        Subtitle = 17,
        Buttons = 18,
        Control = 32,
        Metadata = 33,
    };
    TrackTranslateCodec {
        MatroskaScript = 0,
        DvdMenu = 1,
    };
    FlagInterlaced {
        Undetermined = 0,
        Interlaced = 1,
        Progressive = 2,
    };
    FieldOrder {
        Progressive = 0,
        Tff = 1,
        Undetermined = 2,
        Bff = 6,
        BffSwapped = 9,
        TffSwapped = 14,
    };
    StereoMode {
        Mono = 0,
        SideBySideLeftEyeFirst = 1,
        TopBottomRightEyeIsFirst = 2,
        TopBottomLeftEyeIsFirst = 3,
        CheckboardRightEyeIsFirst = 4,
        CheckboardLeftEyeIsFirst = 5,
        RowInterleavedRightEyeIsFirst = 6,
        RowInterleavedLeftEyeIsFirst = 7,
        ColumnInterleavedRightEyeIsFirst = 8,
        ColumnInterleavedLeftEyeIsFirst = 9,
        AnaglyphCyanRed = 10,
        SideBySideRightEyeFirst = 11,
        AnaglyphGreenMagenta = 12,
        BothEyesLacedInOneBlockLeftEyeIsFirst = 13,
        BothEyesLacedInOneBlockRightEyeIsFirst = 14,
    };
    AlphaMode {
        None = 0,
        Present = 1,
    };
    OldStereoMode {
        Mono = 0,
        RightEye = 1,
        LeftEye = 2,
        BothEyes = 3,
    };
    DisplayUnit {
        Pixels = 0,
        Centimeters = 1,
        Inches = 2,
        DisplayAspectRatio = 3,
        Unknown = 4,
    };
    AspectRatioType {
        FreeResizing = 0,
        KeepAspectRatio = 1,
        Fixed = 2,
    };
    MatrixCoefficients {
        Identity = 0,
        ItuRBt709 = 1,
        Unspecified = 2,
        Reserved1 = 3,
        UsFcc73682 = 4,
        ItuRBt470Bg = 5,
        Smpte170M = 6,
        Smpte240M = 7,
        YCoCg = 8,
        Bt2020NonConstantLuminance = 9,
        Bt2020ConstantLuminance = 10,
        SmpteSt2085 = 11,
        ChromaDerivedNonConstantLuminance = 12,
        ChromaDerivedConstantLuminance = 13,
        ItuRBt21000 = 14,
    };
    ChromaSitingHorz {
        Unspecified = 0,
        LeftCollocated = 1,
        Half = 2,
    };
    ChromaSitingVert {
        Unspecified = 0,
        TopCollocated = 1,
        Half = 2,
    };
    Range {
        Unspecified = 0,
        BroadcastRange = 1,
        FullRangeNoClipping = 2,
        DefinedByMatrixCoefficientsTransferCharacteristics = 3,
    };
    TransferCharacteristics {
        Reserved1 = 0,
        ItuRBt709 = 1,
        Unspecified = 2,
        Reserved2 = 3,
        Gamma22CurveBt470M = 4,
        Gamma28CurveBt470Bg = 5,
        Smpte170M = 6,
        Smpte240M = 7,
        Linear = 8,
        Log = 9,
        LogSqrt = 10,
        Iec6196624 = 11,
        ItuRBt1361ExtendedColourGamut = 12,
        Iec6196621 = 13,
        ItuRBt202010Bit = 14,
        ItuRBt202012Bit = 15,
        ItuRBt2100PerceptualQuantization = 16,
        SmpteSt4281 = 17,
        AribStdB67Hlg = 18,
    };
    Primaries {
        Reserved1 = 0,
        ItuRBt709 = 1,
        Unspecified = 2,
        Reserved2 = 3,
        ItuRBt470M = 4,
        ItuRBt470BgBt601625 = 5,
        ItuRBt601525Smpte170M = 6,
        Smpte240M = 7,
        Film = 8,
        ItuRBt2020 = 9,
        SmpteSt4281 = 10,
        SmpteRp4322 = 11,
        SmpteEg4322 = 12,
        EbuTech3213EJedecP22Phosphors = 22,
    };
    ProjectionType {
        Rectangular = 0,
        Equirectangular = 1,
        Cubemap = 2,
        Mesh = 3,
    };
    TrackPlaneType {
        LeftEye = 0,
        RightEye = 1,
        Background = 2,
    };
    ContentEncodingScope {
        Block = 1,
        Private = 2,
        Next = 4,
    };
    ContentEncodingType {
        Compression = 0,
        Encryption = 1,
    };
    ContentCompAlgo {
        Zlib = 0,
        Bzlib = 1,
        Lzo1X = 2,
        HeaderStripping = 3,
    };
    ContentEncAlgo {
        NotEncrypted = 0,
        Des = 1,
        TripleDes = 2,
        Twofish = 3,
        Blowfish = 4,
        Aes = 5,
    };
    AesSettingsCipherMode {
        AesCtr = 1,
        AesCbc = 2,
    };
    ContentSigAlgo {
        NotSigned = 0,
        Rsa = 1,
    };
    ContentSigHashAlgo {
        NotSigned = 0,
        Sha1160 = 1,
        Md5 = 2,
    };
    ChapProcessTime {
        DuringTheWholeChapter = 0,
        BeforeStartingPlayback = 1,
        AfterPlaybackOfTheChapter = 2,
    };
    TargetTypeValue {
        Collection = 70,
        EditionIssueVolumeOpusSeasonSequel = 60,
        AlbumOperaConcertMovieEpisode = 50,
        PartSession = 40,
        TrackSongChapter = 30,
        SubtrackPartMovementScene = 20,
        Shot = 10,
    };
}
