name: Cross

on:
  push:
    branches:
      - 'main'
      # TODO: remove this once it's been tested on the PR
      - 'cross'
    tags:
      - 'v*'

jobs:
  cross:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - triple: x86_64-unknown-linux-musl
            arch: x86_64
          - triple: aarch64-unknown-linux-musl
            arch: aarch64
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: taiki-e/install-action@cross

      - name: Test
        run: cross test --release --target ${{ matrix.target.triple }}

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: mkvdump-${{ matrix.target.arch }}
          path: target/${{ matrix.target.triple }}/release/mkvdump

  release:
    runs-on: ubuntu-latest
    needs: cross
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3

      - name: Rename files
        run: |
          cp mkvdump-x86_64/mkvdump mkvdump-linux-x86_64
          cp mkvdump-aarch64/mkvdump mkvdump-linux-aarch64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            mkvdump-linux-x86_64
            mkvdump-linux-aarch64

  docker:
    runs-on: ubuntu-latest
    needs: cross
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cadubentzen/mkvdump

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
