name: test

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Toolchain setup
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: cargo install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: cargo llvm-cov
      run: cargo llvm-cov --locked --all-features --lcov --output-path lcov.info

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

  os-check:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macos-latest
          - windows-latest\
    steps:
      - uses: actions/checkout@v3

      - name: Toolchain setup
        uses: dtolnay/rust-toolchain@stable

      - name: Check
        run: cargo check --tests
